import React from 'react';
import { ArrowRight, BookOpen, MessageSquare, ShieldCheck } from 'lucide-react';
import { CHALLENGES, LEVEL_LABELS, MAJOR_LABELS } from '../../shared/catalog.js';
import './ReviewWorkspace.css';

export default function ReviewLanding({ go, onSignup, onOpenPolicy, onSelectChallenge }) {
  return <main className="rw-workspace rw-landing">
    <section className="rw-landing-hero"><div><p className="rw-eyebrow">DÀNH CHO SINH VIÊN MUỐN BẮT ĐẦU TỪ VIỆC THẬT</p><h1>Biến bài tập thành portfolio có minh chứng.</h1><p>Chọn một thử thách vừa sức. Làm sản phẩm của bạn. Nhận phản hồi để biết bước tiếp theo — từ Developer, Marketing đến Thiết kế.</p><div className="rw-actions"><button className="rw-primary" onClick={() => onSignup?.()}>Bắt đầu miễn phí <ArrowRight size={17} /></button><button className="rw-secondary" onClick={() => go('hub')}>Khám phá thử thách</button></div><small>Không cần tải file lên hệ thống. Bắt đầu với đường dẫn sản phẩm bạn đã có.</small></div><aside className="rw-landing-example"><span className="rw-eyebrow">MỘT LỘ TRÌNH NHỎ, CÓ ĐÍCH ĐẾN</span><h2>Từ “đã học”<br />đến “đã làm được”.</h2><div><span>01</span><p><b>Chọn việc vừa sức</b><small>Đề bài, nguồn học và tiêu chí có sẵn.</small></p></div><div><span>02</span><p><b>Gửi minh chứng</b><small>Repository, bản thiết kế hoặc kế hoạch.</small></p></div><div><span>03</span><p><b>Nhận hướng cải thiện</b><small>Kiểm tra sơ bộ hoặc mentor chuyên môn.</small></p></div></aside></section>
    <section className="rw-landing-section"><div className="rw-section-heading"><div><p className="rw-eyebrow">HỌC QUA THỰC HÀNH</p><h2>Bài đầu tiên không cần quá lớn.</h2><p>Bài thực hành do Hub biên soạn theo nội dung học uy tín, có thang đánh giá riêng.</p></div><button className="rw-secondary" onClick={() => go('hub')}>Xem các trình độ <ArrowRight size={16} /></button></div><div className="rw-catalog">{CHALLENGES.filter(c => c.access === 'free' && c.level === 'beginner').slice(0, 3).map(c => <article className="rw-challenge" key={c.id}><div className="rw-card-meta"><span>{MAJOR_LABELS[c.majorKey]}</span><span>Miễn phí</span></div><h3>{c.title}</h3><p>{c.summary}</p><small>{LEVEL_LABELS[c.level]} · Khoảng {c.estimatedHours} giờ</small><a href={c.source.url} target="_blank" rel="noopener noreferrer">Nguồn học: {c.source.name}</a><div className="rw-card-foot"><button onClick={() => onSelectChallenge ? onSelectChallenge(c.id) : go('hub')}>Khám phá yêu cầu <ArrowRight size={15} /></button></div></article>)}</div><p className="rw-muted">Các bài này không phải đề thi chính thức hoặc chứng chỉ của FPT hay Coursera. Chi phí và điều kiện truy cập khóa học do nhà cung cấp quyết định.</p></section>
    <section className="rw-landing-section rw-split"><article className="rw-panel"><BookOpen size={25} /><p className="rw-eyebrow">TỰ CHỦ BẮT ĐẦU</p><h2>Miễn phí để thực hành</h2><p>Chọn bài nền tảng hoặc trung cấp, lưu bản nháp, gửi link và kiểm tra mức độ đầy đủ của minh chứng.</p><ul><li>Không cần tải nhiều file lên hệ thống.</li><li>Tiêu chí chấm rõ ràng trước khi làm.</li><li>Kiểm tra sơ bộ không tự đọc link hay chấm chất lượng sản phẩm.</li></ul><button className="rw-secondary" onClick={() => onSignup?.()}>Tạo tài khoản sinh viên</button></article><article className="rw-panel rw-submit"><MessageSquare size={25} /><p className="rw-eyebrow">PHẢN HỒI CHUYÊN MÔN</p><h2>Premium cùng mentor thật</h2><p>Chọn mentor đã được duyệt và tự tin với bài của bạn. Xem đánh giá, khối lượng chờ và thời gian phản hồi ước tính trước khi gửi.</p><ul><li>Trao đổi bối cảnh và nhận nhận xét theo từng tiêu chí.</li><li>Đánh giá sao sau khi hoàn thành review.</li><li>Hệ thống trích 5.000 đ/bài hoàn thành trả mentor; sinh viên không trả thêm khoản này ngoài gói.</li></ul><button className="rw-primary" onClick={() => go('premium')}>Tìm hiểu Premium <ArrowRight size={16} /></button></article></section>
    <section className="rw-mentor-invite"><div><p className="rw-eyebrow">DÀNH CHO NGƯỜI CÓ KINH NGHIỆM</p><h2>Giúp một sinh viên làm tốt hơn.</h2><p>Đăng ký mentor, gửi CV hoặc đề nghị trao đổi để xác minh. Bạn chọn bài có thể chấm, đặt sức chứa và nhận phí cùng thưởng từ phản hồi sinh viên.</p></div><button className="rw-primary" onClick={() => onSignup?.('mentor')}>Đăng ký làm mentor <ArrowRight size={17} /></button></section>
    <section className="rw-landing-section rw-faq"><p className="rw-eyebrow">TRƯỚC KHI BẠN BẮT ĐẦU</p><h2>Mọi bước đều rõ ràng.</h2>{[
      ['Tôi chưa có kinh nghiệm, nên bắt đầu ở đâu?', 'Chọn bài nền tảng đúng ngành, đọc yêu cầu và nguồn học. Bạn có thể lưu nháp rồi quay lại khi đã có sản phẩm; không cần hoàn thành tất cả trong một lần.'],
      ['Mentor tôi muốn chọn đang quá tải thì sao?', 'Bạn sẽ thấy cảnh báo phản hồi chậm và gợi ý mentor ít bài chờ hơn. Nếu vẫn muốn chọn mentor đó, bạn có thể xác nhận đồng ý chờ. Thời gian hiển thị là ước tính.'],
      ['Tôi nộp bài như thế nào?', 'Gửi tối đa 3 link HTTP/HTTPS cùng kỹ năng và mô tả. Kiểm tra quyền xem trên GitHub, Figma, Drive hoặc nơi bạn lưu bài. Không gửi mật khẩu, thông tin khách hàng hay dữ liệu nhạy cảm.'],
      ['Bài của tôi có tự động chia sẻ với mentor khác không?', 'Không. Mục Sinh viên nổi trội chỉ hiển thị bài đạt từ 85 điểm khi bạn chủ động đồng ý. Bạn có thể thu hồi quyền chia sẻ ở Bài của tôi.'],
      ['AI và mentor thật khác nhau thế nào?', 'Kiểm tra sơ bộ dùng quy tắc để xem thông tin đã đủ chưa. Gợi ý AI, khi máy chủ có cấu hình và bạn đồng ý, chỉ dựa trên ghi chú và kỹ năng. Mentor thật xem minh chứng và đánh giá theo tiêu chí chuyên môn.']
    ].map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    <footer className="rw-footer"><ShieldCheck size={18} /><span>Portfolio FPT Hub · Thực hành có minh chứng, phát triển có định hướng.</span>{onOpenPolicy && <button className="rw-text-button" onClick={() => onOpenPolicy('privacy')}>Chính sách bảo mật</button>}</footer>
  </main>;
}
