import React, { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, ExternalLink, RefreshCw, ShieldCheck, Star } from 'lucide-react';
import { CHALLENGES, RESOURCES, MAJOR_LABELS, LEVEL_LABELS, REVIEW_FEE } from '../../shared/catalog.js';
import { fetchWithAuth } from '../services/api';
import './ReviewWorkspace.css';

const money = n => `${Number(n || 0).toLocaleString('vi-VN')} đ`;
const idOf = x => x?.id || x?._id;
const statuses = { draft: 'Bản nháp', queued: 'Đang chờ mentor', in_review: 'Đang được review', needs_revision: 'Cần bổ sung', completed: 'Đã hoàn thành', cancelled: 'Đã hủy' };
const emptyForm = { format: 'project', links: '', skills: '', notes: '', mode: 'ai', mentorId: '', acceptDelay: false, linksAccessible: false, shareTalent: false };
const safeUrl = url => { try { return ['http:', 'https:'].includes(new URL(url).protocol); } catch { return false; } };
function Link({ url, children }) { return safeUrl(url) ? <a href={url} target="_blank" rel="noopener noreferrer">{children || url} <ExternalLink size={13} /></a> : <span>{children || 'Liên kết không hợp lệ'}</span>; }
function Empty({ children }) { return <div className="rw-empty"><BookOpen size={28} /><p>{children}</p></div>; }
function Field({ label, children, hint }) { return <label className="rw-field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }

export default function ReviewWorkspace({ currentUser, go, initialTab = 'catalog', initialChallengeId }) {
  const role = currentUser?.type || 'guest';
  const mentor = role === 'mentor', admin = role === 'admin';
  const tabs = admin ? [['applications', 'Duyệt mentor'], ['payments', 'Đối soát & chi trả'], ['quality', 'Chất lượng'], ['complaints', 'Khiếu nại']] : mentor ? [['queue', 'Bài cần review'], ['scope', 'Hồ sơ & chuyên môn'], ['earnings', 'Thu nhập'], ['talent', 'Sinh viên nổi trội'], ['support', 'Hỗ trợ']] : [['catalog', 'Khám phá thử thách'], ['submissions', 'Bài của tôi'], ['resources', 'Học liệu'], ['support', 'Hỗ trợ']];
  const normalizeTab = value => tabs.some(([key]) => key === value) ? value : mentor ? 'queue' : admin ? 'applications' : ['submit', 'history', 'feedback'].includes(value) ? 'submissions' : value === 'learning' ? 'resources' : 'catalog';
  const [tab, setTab] = useState(() => normalizeTab(initialTab));
  const [data, setData] = useState({ catalog: CHALLENGES, resources: RESOURCES, mentors: [], submissions: [], orders: [], talents: [], applications: [], complaints: [], earnings: {} });
  const [loading, setLoading] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [online, setOnline] = useState(false);
  const [filters, setFilters] = useState({ major: '', level: '', access: '', query: '' });
  const [selected, setSelected] = useState(null), [form, setForm] = useState(emptyForm), [editingId, setEditingId] = useState(null);
  const [scope, setScope] = useState({ challengeIds: [], capacity: 5, available: true });
  const [application, setApplication] = useState({ method: 'cv', profileUrl: '', notes: '' });
  const [opened, setOpened] = useState(null);
  useEffect(() => { setTab(normalizeTab(initialTab)); setSelected(null); }, [initialTab, role]);
  useEffect(() => { if (initialChallengeId && !mentor && !admin) { const match = CHALLENGES.find(c => c.id === initialChallengeId); if (match) { setSelected(match); setTab('catalog'); setEditingId(null); setForm(emptyForm); } } }, [initialChallengeId, role]);
  async function refresh() {
    setLoading(true); setError('');
    try {
      const next = await fetchWithAuth(role === 'guest' ? '/api/workflow/catalog' : '/api/workflow/state');
      setData(prev => ({ ...prev, ...next })); setOnline(true);
      if (next.profile) setScope({ challengeIds: next.profile.challengeIds || [], capacity: next.profile.capacity || 5, available: next.profile.available !== false });
    } catch (e) { setOnline(false); setError(e.message); }
    finally { setLoading(false); }
  }
  useEffect(() => { refresh(); }, [role, currentUser?.user?.id, currentUser?.user?._id]);
  async function mutate(path, body, method = 'POST', success = 'Đã lưu thay đổi.') {
    if (busy) return false;
    setBusy(true); setError(''); setNotice('');
    try { await fetchWithAuth(`/api/workflow${path}`, { method, body: JSON.stringify(body), ...(path.endsWith('/ai-advice') ? { signal: AbortSignal.timeout(35000) } : {}) }); await refresh(); setNotice(success); return true; }
    catch (e) { setError(e.message); return false; }
    finally { setBusy(false); }
  }
  const catalog = (data.catalog?.length ? data.catalog : CHALLENGES).map(challenge => {
    const localBrief = CHALLENGES.find(item => item.id === challenge.id);
    return localBrief ? {
      ...localBrief,
      ...challenge,
      levelDescription: challenge.levelDescription || localBrief.levelDescription,
      learningOutcome: challenge.learningOutcome || localBrief.learningOutcome
    } : challenge;
  });
  const challengeOf = s => catalog.find(c => c.id === s.challengeId);
  const revising = !!editingId && form.status === 'needs_revision';
  const mentors = (data.mentors || []).filter(m => revising ? m.canContinue && String(idOf(m)) === form.mentorId : m.eligible && m.available !== false && (m.challengeIds || []).includes(selected?.id));
  const chosenMentor = mentors.find(m => String(idOf(m)) === form.mentorId);
  function choose(c) { setSelected(c); setEditingId(null); setForm(emptyForm); setTab('catalog'); setError(''); }
  function edit(s, upgrade = false) { setSelected(challengeOf(s)); setEditingId(idOf(s)); setForm({ ...emptyForm, ...s, mode: upgrade ? 'human' : s.mode, links: (s.links || []).join('\n'), skills: (s.skills || []).join(', '), mentorId: String(s.mentorId || '') }); setTab('catalog'); }
  async function submit(status) {
    if (role === 'guest') { go('auth'); return; }
    const links = form.links.split('\n').map(s => s.trim()).filter(Boolean);
    const skills = form.skills.split(',').map(s => s.trim()).filter(Boolean);
    if (links.length > 3 || links.some(url => !safeUrl(url))) { setError('Dùng tối đa 3 đường dẫn HTTP/HTTPS hợp lệ.'); return; }
    if (skills.length > 15) { setError('Vui lòng nhập tối đa 15 kỹ năng.'); return; }
    if (status !== 'draft' && (form.notes.trim().length < 40 || skills.length < 2 || (form.format !== 'chat' && !links.length) || (links.length && !form.linksAccessible))) { setError('Cần mô tả ít nhất 40 ký tự, ít nhất 2 kỹ năng, đường dẫn minh chứng và xác nhận quyền truy cập.'); return; }
    const ok = await mutate(`/submissions${editingId ? `/${editingId}` : ''}`, { ...form, links, skills, challengeId: selected.id, status }, editingId ? 'PUT' : 'POST', status === 'draft' ? 'Đã lưu bản nháp.' : 'Đã tiếp nhận bài nộp. Xem kết quả và trạng thái bên dưới.');
    if (ok) { setSelected(null); setEditingId(null); setTab('submissions'); }
  }
  const gated = selected?.access === 'premium' && !data.paid;
  return <main className="rw-workspace">
    <header className="rw-header"><div><p className="rw-eyebrow">PORTFOLIO FPT HUB / THỰC HÀNH & PHẢN HỒI</p><h1>{admin ? 'Vận hành có kiểm chứng.' : mentor ? 'Kinh nghiệm của bạn. Bước tiến của sinh viên.' : 'Làm một bài thật. Tiến thêm một bước.'}</h1><p>{admin ? 'Duyệt năng lực mentor, theo dõi đánh giá và xác nhận giao dịch thực tế.' : mentor ? 'Chọn đúng chuyên môn, chủ động khối lượng và nhận phí cho mỗi bài hoàn thành.' : 'Chọn thử thách phù hợp, nộp đường dẫn sản phẩm và nhận hướng dẫn cải thiện.'}</p></div><button className="rw-secondary" onClick={refresh} disabled={loading || busy}><RefreshCw size={16} />{loading ? 'Đang tải…' : 'Làm mới'}</button></header>
    {!mentor && !admin && <ol className="rw-steps"><li><b>01</b> Chọn thử thách</li><li><b>02</b> Nộp minh chứng</li><li><b>03</b> Nhận phản hồi</li></ol>}
    <nav className="rw-tabs" aria-label="Không gian thực hành">{tabs.map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => { setTab(key); setSelected(null); }}>{label}</button>)}</nav>
    {error && <div className="rw-alert rw-error" role="alert">{error}</div>}
    {notice && <div className="rw-alert rw-success" role="status">{notice}</div>}
    {!online && !loading && <div className="rw-alert">Bạn đang xem học liệu có sẵn. Cần kết nối máy chủ để lưu bài, review, đối soát và xem dữ liệu tài khoản.</div>}
    {tab === 'catalog' && !selected && <>
      <div className="rw-section-heading"><div><h2>Bắt đầu từ điều bạn muốn làm tốt</h2><p>Bài thực hành do Hub biên soạn, có nguồn học và tiêu chí rõ ràng.</p></div><span className="rw-badge">{data.paid ? 'Tài khoản Premium' : 'Có thử thách miễn phí'}</span></div>
      <div className="rw-filters"><Field label="Tìm thử thách"><input value={filters.query} onChange={e => setFilters({ ...filters, query: e.target.value })} placeholder="Tên hoặc kỹ năng…" /></Field><Field label="Ngành"><select value={filters.major} onChange={e => setFilters({ ...filters, major: e.target.value })}><option value="">Tất cả ngành</option>{Object.entries(MAJOR_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></Field><Field label="Trình độ"><select value={filters.level} onChange={e => setFilters({ ...filters, level: e.target.value })}><option value="">Tất cả trình độ</option>{Object.entries(LEVEL_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></Field><Field label="Quyền truy cập"><select value={filters.access} onChange={e => setFilters({ ...filters, access: e.target.value })}><option value="">Tất cả</option><option value="free">Miễn phí</option><option value="premium">Premium</option></select></Field></div>
      <div className="rw-catalog">{catalog.filter(c => (!filters.major || c.majorKey === filters.major) && (!filters.level || c.level === filters.level) && (!filters.access || c.access === filters.access) && `${c.title} ${c.summary}`.toLocaleLowerCase('vi').includes(filters.query.toLocaleLowerCase('vi'))).sort((a, b) => Number(a.access === 'premium') - Number(b.access === 'premium')).map(c => <article key={c.id} className="rw-challenge"><div className="rw-card-meta"><span>{MAJOR_LABELS[c.majorKey]}</span><span>{c.access === 'premium' ? 'Premium · cần nâng cấp' : 'Miễn phí'}</span></div><h3>{c.title}</h3><p>{c.summary}</p><div className="rw-card-outcome"><small>Đầu ra sau bài tập</small><p>{c.learningOutcome || 'Hoàn thành sản phẩm theo yêu cầu và lưu lại minh chứng để bổ sung vào portfolio.'}</p></div><div className="rw-card-requirements"><strong>Yêu cầu chính</strong><ul>{c.requirements.slice(0, 2).map((item, i) => <li key={i}>{item}</li>)}</ul></div><p className="rw-card-level-help">{c.levelDescription || 'Xem chi tiết để biết yêu cầu và tiêu chí chấm của bài tập.'}</p><div className="rw-card-foot"><span>{LEVEL_LABELS[c.level]} · khoảng {c.estimatedHours} giờ · {c.rubric.length} tiêu chí</span><button onClick={() => choose(c)}>Xem yêu cầu <ArrowRight size={16} /></button></div><small>Nguồn học: {c.source?.name}</small></article>)}</div>
      {!catalog.some(c => (!filters.major || c.majorKey === filters.major) && (!filters.level || c.level === filters.level) && (!filters.access || c.access === filters.access) && `${c.title} ${c.summary}`.toLocaleLowerCase('vi').includes(filters.query.toLocaleLowerCase('vi'))) && <Empty>Chưa có thử thách khớp bộ lọc. Hãy thử ngành hoặc trình độ khác.</Empty>}
    </>}
    {selected && tab === 'catalog' && <div className="rw-split"><section className="rw-panel"><button className="rw-text-button" onClick={() => setSelected(null)}>← Tất cả thử thách</button><p className="rw-eyebrow">{MAJOR_LABELS[selected.majorKey]} / {LEVEL_LABELS[selected.level]} / {selected.estimatedHours} giờ dự kiến</p><h2>{selected.title}</h2><p>{selected.summary}</p><div className="rw-detail-level"><strong>Độ khó: {LEVEL_LABELS[selected.level]}</strong><p>{selected.levelDescription || 'Hoàn thành các yêu cầu và xem rubric để hiểu cách mentor đánh giá.'}</p></div><div className="rw-detail-outcome"><small>Bạn sẽ có gì sau khi hoàn thành?</small><p>{selected.learningOutcome || 'Một sản phẩm theo đúng đề bài, có minh chứng và có thể đưa vào portfolio.'}</p></div><h3>Yêu cầu bắt buộc và minh chứng cần nộp</h3><ul className="rw-detail-requirements">{selected.requirements.map((r, i) => <li key={i}>{r}</li>)}</ul><div className="rw-source"><BookOpen size={20} /><div><Link url={selected.source?.url}>{selected.source?.name}</Link><p>{selected.source?.note}</p></div></div><h3>Mentor sẽ đánh giá như thế nào?</h3><Rubric challenge={selected} /><p className="rw-muted">Điểm review phản ánh minh chứng của bài này, không phải chứng chỉ từ đơn vị cung cấp học liệu.</p></section>
      <section className="rw-panel rw-submit"><h2>{editingId ? 'Chỉnh sửa bài nộp' : 'Chuẩn bị bài của bạn'}</h2><p>Chỉ gửi đường dẫn. Giữ mã nguồn, CV và thiết kế trên dịch vụ lưu trữ bạn quản lý.</p>{gated && <div className="rw-alert">Cần Premium đã được xác nhận để lưu nháp hoặc nộp thử thách này. <button onClick={() => go('premium')}>Xem gói nâng cấp</button></div>}
      <Field label="Cách gửi minh chứng"><select value={form.format} onChange={e => setForm({ ...form, format: e.target.value, mode: e.target.value === 'chat' ? 'human' : form.mode })}><option value="project">Sản phẩm / bài thực hành</option><option value="cv">CV và minh chứng năng lực</option><option value="chat">Trao đổi bối cảnh với mentor</option></select></Field>
      {form.format !== 'project' && <p className="rw-muted">Mentor dùng tiêu chí của thử thách để trao đổi về năng lực; đây không phải lịch hẹn trực tuyến.</p>}
      <Field label="Đường dẫn minh chứng" hint="Tối đa 3 link, mỗi dòng một link: GitHub, Figma, Google Drive…"><textarea value={form.links} onChange={e => setForm({ ...form, links: e.target.value })} placeholder="https://…" rows={3} maxLength={6000} /></Field>
      <label className="rw-check"><input type="checkbox" checked={form.linksAccessible} onChange={e => setForm({ ...form, linksAccessible: e.target.checked })} />Tôi đã kiểm tra người có đường dẫn có thể xem bài; không đưa mật khẩu hoặc dữ liệu nhạy cảm vào minh chứng.</label>
      <Field label="Kỹ năng đã vận dụng" hint="Ngăn cách bằng dấu phẩy, từ 2 đến 15 kỹ năng."><input value={form.skills} onChange={e => setForm({ ...form, skills: e.target.value })} maxLength={1000} /></Field>
      <Field label="Bạn đã làm gì và muốn được góp ý điều gì?" hint={`${form.notes.length}/3000 ký tự · Tối thiểu 40 khi nộp bài`}><textarea rows={4} maxLength={3000} value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field>
      {revising && <p className="rw-alert">Bài bổ sung gửi lại mentor đang review. Nếu mentor bị tạm ngưng, hãy vào Bài của tôi, hủy bài rồi chỉnh sửa để chọn mentor khác.</p>}<fieldset className="rw-modes"><legend>Chọn hình thức phản hồi</legend><label className={form.mode === 'ai' ? 'selected' : ''}><input type="radio" name="reviewMode" disabled={form.format === 'chat' || revising} checked={form.mode === 'ai'} onChange={() => setForm({ ...form, mode: 'ai', mentorId: '' })} /><div><strong>AI · Kiểm tra sơ bộ</strong><small>Miễn phí. Kiểm tra cấu trúc thông tin; không mở link, chạy code hay chấm chuyên môn.</small></div></label><label className={form.mode === 'human' ? 'selected' : ''}><input type="radio" name="reviewMode" disabled={revising} checked={form.mode === 'human'} onChange={() => setForm({ ...form, mode: 'human' })} /><div><strong>Mentor thật · Review chuyên môn</strong><small>Dành cho Premium. Mentor nhận {money(REVIEW_FEE)} / bài hoàn thành từ hệ thống.</small></div></label></fieldset>
      {form.mode === 'human' && <><Field label="Mentor phù hợp với thử thách"><select disabled={revising} value={form.mentorId} onChange={e => setForm({ ...form, mentorId: e.target.value, acceptDelay: false })}><option value="">Chọn mentor</option>{mentors.map(m => <option value={idOf(m)} key={idOf(m)}>{m.name} · {Number(m.ratingAvg || 0).toFixed(1)}★ ({m.ratingCount || 0}) · {m.queueCount}/{m.capacity} bài · ~{m.estimatedDays} ngày</option>)}</select></Field>{!mentors.length && <p className="rw-muted">Chưa có mentor đã được duyệt nhận chấm thử thách này. Tài khoản Premium có thể lưu nháp; nếu chưa nâng cấp, hãy chọn kiểm tra sơ bộ với bài miễn phí.</p>}{chosenMentor?.overloaded && !revising && <div className="rw-alert"><strong>Mentor đang quá tải, phản hồi sẽ chậm đáng kể.</strong><p>Ước tính {chosenMentor.estimatedDays} ngày. Bạn vẫn có thể chọn nếu đồng ý chờ.</p>{mentors.filter(m => !m.overloaded && idOf(m) !== idOf(chosenMentor)).slice(0, 3).map(m => <button key={idOf(m)} className="rw-secondary" onClick={() => setForm({ ...form, mentorId: String(idOf(m)), acceptDelay: false })}>Chọn {m.name} · {Number(m.ratingAvg || 0).toFixed(1)}★</button>)}<label className="rw-check"><input type="checkbox" checked={form.acceptDelay} onChange={e => setForm({ ...form, acceptDelay: e.target.checked })} />Tôi đồng ý thời gian phản hồi chậm.</label></div>}{!data.paid && <p className="rw-alert">Cần Premium đã được xác nhận để lưu nháp hoặc gửi bài cho mentor thật. <button onClick={() => go('premium')}>Xem Premium</button></p>}</>}
      <label className="rw-check"><input type="checkbox" checked={form.shareTalent} onChange={e => setForm({ ...form, shareTalent: e.target.checked })} />Cho mentor xem bài đạt từ 85 điểm trong mục Sinh viên nổi trội, gồm tên, minh chứng và mô tả. Có thể thu hồi ở Bài của tôi.</label>
      <div className="rw-actions"><button className="rw-secondary" disabled={busy || !online || role === 'guest' || gated || (form.mode === 'human' && !data.paid)} onClick={() => submit('draft')}>Lưu nháp</button><button className="rw-primary" disabled={busy || (role !== 'guest' && (!online || gated || (form.mode === 'human' && (!data.paid || !chosenMentor || (chosenMentor.overloaded && !revising && !form.acceptDelay)))))} onClick={() => submit('queued')}>{busy ? 'Đang gửi…' : role === 'guest' ? 'Đăng nhập để nộp bài' : 'Gửi bài'} <ArrowRight size={16} /></button></div></section></div>}
    {tab === 'resources' && <section><div className="rw-section-heading"><div><h2>Học từ nguồn rõ ràng</h2><p>Truy cập trực tiếp nhà cung cấp. Quyền truy cập và chi phí khóa học do từng nguồn quy định.</p></div></div><div className="rw-resource-list">{(data.resources || []).map(r => <article className="rw-panel" key={r.id}><span className="rw-eyebrow">{r.source} · {MAJOR_LABELS[r.majorKey] || 'Liên ngành'}</span><h3><Link url={r.url}>{r.title}</Link></h3><p>{r.note}</p></article>)}</div></section>}
    {['submissions', 'queue'].includes(tab) && <section><div className="rw-section-heading"><div><h2>{mentor ? 'Hàng đợi review của bạn' : 'Theo dõi từng bước tiến'}</h2><p>{mentor ? 'Bắt đầu bài trước khi chấm. Yêu cầu bổ sung nếu minh chứng chưa đủ.' : 'AI sơ bộ và mentor chuyên môn được lưu riêng cho từng lượt nộp.'}</p></div></div>{!(data.submissions || []).length ? <Empty>{role === 'guest' ? 'Đăng nhập để xem và lưu bài thực hành của bạn.' : 'Chưa có bài nộp. Mỗi tiến bộ bắt đầu từ một sản phẩm nhỏ.'}</Empty> : <div className="rw-list">{data.submissions.map(s => <Submission key={idOf(s)} submission={s} challenge={challengeOf(s)} mentor={mentor} aiEnabled={data.aiEnabled} busy={busy} mutate={mutate} onEdit={(upgrade) => edit(s, upgrade)} opened={opened === idOf(s)} onOpen={() => setOpened(opened === idOf(s) ? null : idOf(s))} />)}</div>}{!mentor && role === 'student' && <SupportTicketForm busy={busy} mutate={mutate} kind="review" submissions={data.submissions || []} />}</section>}
    {tab === 'scope' && <div className="rw-split"><section className="rw-panel"><h2>Xác minh hồ sơ mentor</h2><p>Chỉ mentor được Admin duyệt mới xuất hiện trong danh sách sinh viên có thể chọn.</p><div className="rw-alert">Trạng thái: <strong>{({ approved: 'Đã được duyệt', pending: 'Đang chờ duyệt', rejected: 'Cần điều chỉnh', suspended: 'Tạm ngưng' })[data.profile?.application?.status] || 'Chưa gửi hồ sơ'}</strong>{data.profile?.application?.reason && <p>{data.profile.application.reason}</p>}</div><Field label="Cách xác minh"><select value={application.method} onChange={e => setApplication({ ...application, method: e.target.value })}><option value="cv">Gửi đường dẫn CV / hồ sơ chuyên môn</option><option value="chat">Đề nghị trao đổi với Admin</option></select></Field><Field label="Đường dẫn CV / portfolio"><input type="url" value={application.profileUrl} maxLength={500} onChange={e => setApplication({ ...application, profileUrl: e.target.value })} placeholder="https://…" /></Field><Field label="Kinh nghiệm, chuyên môn và nội dung muốn trao đổi" hint="Tối thiểu 40 ký tự. Đề nghị trao đổi sẽ được Admin xem xét, không tự tạo cuộc hẹn."><textarea rows={5} maxLength={3000} value={application.notes} onChange={e => setApplication({ ...application, notes: e.target.value })} /></Field><button className="rw-primary" disabled={busy || !online || ['approved', 'suspended'].includes(data.profile?.application?.status) || application.notes.trim().length < 40 || (application.method === 'cv' && !safeUrl(application.profileUrl))} onClick={() => mutate('/mentor/application', application)}>Gửi hồ sơ xét duyệt</button></section><section className="rw-panel"><h2>Bạn tự tin review nội dung nào?</h2><p>Chọn đúng bài và trình độ bạn có thể hướng dẫn. Sinh viên chỉ thấy bạn ở các bài này sau khi hồ sơ được duyệt.</p><div className="rw-scope-list">{catalog.map(c => <label className="rw-check" key={c.id}><input type="checkbox" checked={scope.challengeIds.includes(c.id)} onChange={e => setScope({ ...scope, challengeIds: e.target.checked ? [...scope.challengeIds, c.id] : scope.challengeIds.filter(id => id !== c.id) })} /><span>{c.title}<small>{MAJOR_LABELS[c.majorKey]} · {LEVEL_LABELS[c.level]}</small></span></label>)}</div><Field label="Số bài có thể xử lý cùng lúc (1–20)"><input type="number" min="1" max="20" value={scope.capacity} onChange={e => setScope({ ...scope, capacity: Number(e.target.value) })} /></Field><label className="rw-check"><input type="checkbox" checked={scope.available} onChange={e => setScope({ ...scope, available: e.target.checked })} />Tôi đang sẵn sàng nhận bài mới</label><p className="rw-muted">Khi vượt ngưỡng, sinh viên nhận cảnh báo chậm và được gợi ý mentor khác. Họ vẫn có thể chọn bạn sau khi xác nhận chờ.</p><button className="rw-primary" disabled={busy || !online || scope.capacity < 1 || scope.capacity > 20} onClick={() => mutate('/mentor/profile', scope, 'PUT')}>Lưu chuyên môn & sức chứa</button></section></div>}
    {tab === 'earnings' && <section><h2>Thu nhập từ review đã hoàn thành</h2><p>Phí cơ bản {money(REVIEW_FEE)}/bài. Sinh viên chấm 4★ thưởng 750 đ, 5★ thưởng 1.250 đ. Mỗi bài chỉ ghi nhận một lần; hệ thống không tự chuyển tiền.</p><div className="rw-metrics">{[['count', 'Bài hoàn thành'], ['base', 'Phí cơ bản'], ['bonus', 'Thưởng đánh giá'], ['pending', 'Chờ chi trả'], ['paid', 'Đã ghi nhận chi trả']].map(([key, label]) => <div key={key}><small>{label}</small><strong>{key === 'count' ? data.earnings?.[key] || 0 : money(data.earnings?.[key])}</strong></div>)}</div><RewardList submissions={data.submissions || []} catalog={catalog} /><SupportTicketForm busy={busy} mutate={mutate} kind="payout" /></section>}
    {tab === 'talent' && <section><h2>Sinh viên nổi trội</h2><p>Các bài đạt từ 85 điểm và được sinh viên chủ động cho phép chia sẻ. Dùng để tìm hiểu năng lực và định hướng; không tự gửi lời mời tuyển dụng.</p>{!data.talents?.length ? <Empty>Chưa có bài nổi trội được đồng ý chia sẻ.</Empty> : data.talents.map(t => <article className="rw-panel" key={idOf(t)}><span className="rw-badge">{t.score}/100</span><h3>{t.studentName}</h3><p>{catalog.find(c => c.id === t.challengeId)?.title}</p><p>{t.notes}</p><Evidence links={t.links} /></article>)}</section>}
    {tab === 'applications' && <section><h2>Hồ sơ chờ xác minh</h2><p>Kiểm tra CV, minh chứng và năng lực trước khi cho phép nhận bài. Với yêu cầu trao đổi, ghi rõ phản hồi và hướng dẫn trong lý do duyệt.</p>{!data.applications?.length ? <Empty>Chưa có hồ sơ mentor.</Empty> : data.applications.map(p => <AdminMentor key={p.mentorId || idOf(p)} profile={p} mutate={mutate} busy={busy} />)}</section>}
    {tab === 'quality' && <section><h2>Chất lượng từ phản hồi sinh viên</h2><p>Cảnh báo khi có đánh giá ≤2★ hoặc trung bình dưới 3,5★ từ 3 lượt. Tự loại khỏi danh sách nhận bài khi trung bình dưới 2,5★ từ 5 lượt. Admin cần xem xét minh chứng trước quyết định tiếp theo.</p>{!data.mentors?.length ? <Empty>Chưa có dữ liệu mentor để sàng lọc.</Empty> : data.mentors.map(m => <AdminMentor key={idOf(m)} profile={{ ...m, mentorId: idOf(m) }} quality mutate={mutate} busy={busy} />)}</section>}
    {tab === 'payments' && <section><h2>Đối soát Premium</h2><p>Chỉ xác nhận sau khi kiểm tra giao dịch thực tế. Thao tác dưới đây ghi nhận sổ sách, không thực hiện chuyển tiền.</p>{!(data.orders || []).length && <Empty>Chưa có đơn hàng cần theo dõi.</Empty>}{(data.orders || []).map(o => <Payment key={o.orderId} order={o} busy={busy} mutate={mutate} />)}<h2 className="rw-space">Chi trả phí review</h2><RewardList submissions={data.submissions || []} catalog={catalog} admin busy={busy} mutate={mutate} /></section>}
    {tab === 'complaints' && <section><h2>Hàng đợi khiếu nại & hỗ trợ</h2><p>Phân loại review, lương, tài khoản và xử lý theo bằng chứng. Mọi quyết định cần ghi lý do để người gửi theo dõi.</p><div className="rw-metrics">{[['open', 'Mới'], ['in_review', 'Đang xử lý'], ['resolved', 'Đã giải quyết']].map(([status, label]) => <div key={status}><small>{label}</small><strong>{(data.complaints || []).filter(item => item.status === status).length}</strong></div>)}</div>{!(data.complaints || []).length ? <Empty>Chưa có yêu cầu cần xử lý.</Empty> : data.complaints.map(item => <ComplaintItem key={item.id} item={item} busy={busy} mutate={mutate} />)}</section>}
    {tab === 'support' && <section><h2>Yêu cầu hỗ trợ của bạn</h2><p>Theo dõi trạng thái và kết luận của admin. Tối đa 5 yêu cầu mỗi ngày.</p><SupportTicketForm busy={busy} mutate={mutate} kind={mentor ? 'payout' : 'review'} submissions={data.submissions || []} /><TicketHistory items={data.complaints || []} />{!data.complaints?.length && <Empty>Bạn chưa gửi yêu cầu hỗ trợ.</Empty>}</section>}
    <footer className="rw-footer"><ShieldCheck size={17} />Minh chứng có nguồn. Phản hồi có trách nhiệm. Dữ liệu chia sẻ theo lựa chọn của bạn.</footer>
  </main>;
}

function Rubric({ challenge, scores, setScores }) { return <div className="rw-rubric">{(challenge?.rubric || []).map(r => <div key={r.key}><span>{r.label}</span><b>{r.weight}%</b>{setScores && <label>Điểm /10<input aria-label={`Điểm ${r.label}`} type="number" min="0" max="10" step="0.5" value={scores[r.key] ?? ''} onChange={e => setScores({ ...scores, [r.key]: e.target.value === '' ? '' : Number(e.target.value) })} /></label>}</div>)}</div>; }
function Evidence({ links = [] }) { return <div className="rw-evidence">{links.map((link, i) => <Link key={`${link}-${i}`} url={link}>Minh chứng {i + 1}</Link>)}</div>; }
function Submission({ submission: s, challenge, mentor, aiEnabled, busy, mutate, onEdit, opened, onOpen }) {
  const [scores, setScores] = useState({}), [review, setReview] = useState({ strengths: '', improvements: '', comment: '' });
  const [rating, setRating] = useState({ stars: 5, comment: '' }), [message, setMessage] = useState('');
  const [aiConsent, setAiConsent] = useState(false);
  const base = `/submissions/${idOf(s)}`;
  const canChat = s.mode === 'human' && ['queued', 'in_review', 'needs_revision'].includes(s.status);
  const canComplete = challenge?.rubric?.every(r => scores[r.key] !== '' && Number.isFinite(scores[r.key]) && scores[r.key] >= 0 && scores[r.key] <= 10);
  return <article className="rw-submission"><div className="rw-submission-heading"><div><span className={`rw-badge rw-status-${s.status}`}>{statuses[s.status] || s.status}</span><h3>{challenge?.title || s.challengeId}</h3><p>{s.mode === 'human' ? 'Mentor thật' : 'AI · kiểm tra sơ bộ'}{mentor && s.studentName ? ` · ${s.studentName}` : ''}{s.mentorName ? ` · ${s.mentorName}` : ''}</p></div><button className="rw-secondary" onClick={onOpen}>{opened ? 'Thu gọn' : 'Xem bài & phản hồi'}</button></div>{opened && <div className="rw-submission-body"><p>{s.notes}</p><Evidence links={s.links} /><p className="rw-muted">{(s.skills || []).join(' · ')}</p>
    {s.mode === 'ai' && (s.ai || s.aiResult) && <div className="rw-result"><h4>Kiểm tra sơ bộ · {(s.ai || s.aiResult).score}/100</h4><p>{(s.ai || s.aiResult).note}</p>{((s.ai || s.aiResult).checks || []).map((c, i) => <p key={i}>{c.ok ? '✓' : '○'} {c.label}</p>)}</div>}
    {s.mode === 'ai' && s.status === 'completed' && <section className="rw-result"><h4>Gợi ý cải thiện bằng AI</h4>{s.ai?.modelFeedback ? <><p>{s.ai.modelFeedback.summary}</p><ul>{(s.ai.modelFeedback.improvements || []).map((item, index) => <li key={index}>{item}</li>)}</ul><p className="rw-muted">{s.ai.modelFeedback.note}</p></> : aiEnabled ? <><p>Nhận gợi ý từ phần mô tả. AI không truy cập sản phẩm và không thay thế đánh giá chuyên môn của mentor.</p><label className="rw-check"><input type="checkbox" checked={aiConsent} onChange={e => setAiConsent(e.target.checked)} />Gửi ghi chú và kỹ năng cho OpenAI để nhận gợi ý; không gửi link/tài khoản. Không nhập dữ liệu nhạy cảm.</label><button className="rw-secondary" disabled={busy || !aiConsent} onClick={() => mutate(`${base}/ai-advice`, { consent: true }, 'POST', 'Đã nhận gợi ý AI.')}>Nhận gợi ý AI</button></> : <p>Tính năng gợi ý AI chưa được cấu hình trên máy chủ. Bạn vẫn có thể dùng kiểm tra mức độ sẵn sàng hoặc chọn mentor thật.</p>}</section>}
    {s.review && <div className="rw-result"><h4>Phản hồi mentor · {s.review.score}/100</h4><p><strong>Điểm mạnh:</strong> {s.review.strengths}</p><p><strong>Cần cải thiện:</strong> {s.review.improvements}</p><p>{s.review.comment}</p>{challenge?.rubric?.map(r => <p key={r.key}>{r.label}: {s.review.scores?.[r.key] ?? '—'}/10 · trọng số {r.weight}%</p>)}</div>}
    {!mentor && <div className="rw-actions">{['draft', 'needs_revision', 'cancelled'].includes(s.status) && <button className="rw-primary" onClick={() => onEdit(false)}>Chỉnh sửa & nộp lại</button>}{s.mode === 'ai' && s.status === 'completed' && <button className="rw-primary" onClick={() => onEdit(true)}>Gửi mentor thật review</button>}{['draft', 'queued', 'needs_revision'].includes(s.status) && <button className="rw-secondary" disabled={busy} onClick={() => mutate(`${base}/cancel`, {}, 'PATCH', 'Đã hủy bài nộp.')}>Hủy bài nộp</button>}</div>}
    {!mentor && <label className="rw-check"><input type="checkbox" disabled={busy} checked={!!s.shareTalent} onChange={e => mutate(`${base}/consent`, { shareTalent: e.target.checked }, 'PATCH')} />Cho phép chia sẻ bài nổi trội với mentor (có thể thu hồi).</label>}
    {mentor && s.status === 'queued' && <button className="rw-primary" disabled={busy} onClick={() => mutate(`${base}/start`, {}, 'POST', 'Đã bắt đầu review bài này.')}>Bắt đầu review</button>}
    {mentor && s.status === 'in_review' && <section className="rw-review-form"><h4>Chấm theo tiêu chí bài thực hành</h4><Rubric challenge={challenge} scores={scores} setScores={setScores} />{[['strengths', 'Điểm mạnh'], ['improvements', 'Hướng cải thiện'], ['comment', 'Nhận xét / lý do yêu cầu bổ sung']].map(([key, label]) => <Field key={key} label={label}><textarea rows={3} maxLength={3000} value={review[key]} onChange={e => setReview({ ...review, [key]: e.target.value })} /></Field>)}<div className="rw-actions"><button className="rw-secondary" disabled={busy || review.comment.trim().length < 20} onClick={() => mutate(`${base}/review`, { ...review, scores, decision: 'revise' })}>Yêu cầu bổ sung</button><button className="rw-primary" disabled={busy || !canComplete || review.comment.trim().length < 20 || !review.strengths.trim() || !review.improvements.trim()} onClick={() => mutate(`${base}/review`, { ...review, scores, decision: 'complete' }, 'POST', 'Đã hoàn thành review. Phí được ghi nhận trong thu nhập.')}>Hoàn thành review</button></div></section>}
    {!mentor && s.status === 'completed' && s.mode === 'human' && s.paidAtSubmission && !s.rating && !s.reward?.paid && <section className="rw-review-form"><h4>Phản hồi này có giúp ích cho bạn?</h4><p>Bạn có ít nhất 7 ngày từ khi hoàn thành review để đánh giá. Sau thời gian này, đánh giá vẫn mở cho đến khi phí mentor được chi trả. Chỉ gửi một lần; phản hồi giúp cải thiện và sàng lọc mentor.</p><Field label="Số sao"><select value={rating.stars} onChange={e => setRating({ ...rating, stars: Number(e.target.value) })}>{[5, 4, 3, 2, 1].map(n => <option key={n} value={n}>{n} sao</option>)}</select></Field><Field label="Nhận xét"><textarea maxLength={1000} value={rating.comment} onChange={e => setRating({ ...rating, comment: e.target.value })} /></Field><button className="rw-primary" disabled={busy || !!s.reward?.paid} onClick={() => mutate(`${base}/rating`, rating)}>Gửi đánh giá</button></section>}
    {!mentor && s.mode === 'human' && s.status === 'completed' && !s.rating && s.reward?.paid && <p className="rw-alert">Phí review đã được chi trả sau thời gian chờ đánh giá. Lượt đánh giá cho bài này đã đóng; bạn có thể liên hệ hỗ trợ nếu cần phản ánh về chất lượng.</p>}
    {s.rating && <p><Star size={15} /> Đánh giá: {s.rating.stars}/5 · {s.rating.comment}</p>}
    {(canChat || s.messages?.length > 0) && <section className="rw-chat"><h4>Trao đổi với mentor</h4><p className="rw-muted">Bấm Làm mới để nhận tin mới. Tránh gửi thông tin nhạy cảm.</p>{!(s.messages || []).length && <p>Chưa có tin nhắn.</p>}{(s.messages || []).map((m, i) => <div className="rw-message" key={m.id || i}><strong>{m.senderName}</strong><p>{m.text}</p><small>{m.at ? new Date(m.at).toLocaleString('vi-VN') : ''}</small></div>)}{canChat && <><Field label="Nội dung trao đổi"><textarea rows={3} maxLength={2000} value={message} onChange={e => setMessage(e.target.value)} /></Field><button className="rw-secondary" disabled={busy || !message.trim()} onClick={async () => { if (await mutate(`${base}/messages`, { text: message }, 'POST', 'Đã gửi tin nhắn.')) setMessage(''); }}>Gửi tin nhắn</button></>}</section>}
  </div>}</article>;
}
function AdminMentor({ profile: p, quality, mutate, busy }) {
  const [reason, setReason] = useState(''); const application = p.application || p;
  return <article className="rw-panel rw-admin-item"><h3>{p.name || p.mentorName || 'Mentor'}</h3>{quality ? <p>{Number(p.ratingAvg || 0).toFixed(1)}★ / {p.ratingCount || 0} lượt · {p.qualityStatus || 'Chưa đủ đánh giá'} · {p.queueCount || 0} bài chờ</p> : <><p>Trạng thái: {application.status || 'pending'} · {application.method === 'chat' ? 'Đề nghị trao đổi' : 'CV / hồ sơ'}</p>{application.profileUrl && <Link url={application.profileUrl}>Xem hồ sơ chuyên môn</Link>}<p>{application.notes}</p></>}<Field label="Lý do quyết định / phản hồi cho mentor"><textarea maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} /></Field><div className="rw-actions">{(quality ? [['suspended', 'Tạm ngưng nhận bài']] : [['approved', 'Duyệt hồ sơ'], ['rejected', 'Yêu cầu điều chỉnh']]).map(([status, label]) => <button key={status} className={status === 'approved' ? 'rw-primary' : 'rw-secondary'} disabled={busy || reason.trim().length < 10} onClick={() => mutate(`/admin/mentors/${p.mentorId || idOf(p)}`, { status, reason }, 'PATCH')}>{label}</button>)}</div></article>;
}
function SupportTicketForm({ busy, mutate, kind, submissions = [] }) {
  const [submissionId, setSubmissionId] = useState(''), [description, setDescription] = useState('');
  return <section className="rw-panel rw-space"><h3>{kind === 'payout' ? 'Báo vấn đề về khoản thu nhập' : 'Cần hỗ trợ hoặc khiếu nại?'}</h3><p>Gửi mô tả cụ thể, không ghi mật khẩu, số tài khoản hoặc dữ liệu nhạy cảm. Admin phản hồi trong mục khiếu nại.</p>{submissions.length > 0 && <Field label="Bài liên quan"><select value={submissionId} onChange={e => setSubmissionId(e.target.value)}><option value="">Chọn bài liên quan (nếu có)</option>{submissions.map(item => <option value={idOf(item)} key={idOf(item)}>{item.challengeId} · {statuses[item.status]}</option>)}</select></Field>}<Field label="Mô tả vấn đề"><textarea rows={4} maxLength={3000} value={description} onChange={e => setDescription(e.target.value)} placeholder="Nêu thời điểm, điều đã xảy ra và hướng hỗ trợ mong muốn." /></Field><button className="rw-primary" disabled={busy || description.trim().length < 30} onClick={async () => { if (await mutate('/complaints', { kind, submissionId, description }, 'POST', 'Đã gửi yêu cầu hỗ trợ.')) { setDescription(''); setSubmissionId(''); } }}>Gửi yêu cầu hỗ trợ</button></section>;
}
function ComplaintItem({ item, busy, mutate }) {
  const [resolution, setResolution] = useState('');
  return <article className="rw-panel rw-admin-item"><span className={`rw-badge rw-status-${item.status}`}>{item.status === 'open' ? 'Mới' : item.status === 'in_review' ? 'Đang xử lý' : item.status === 'resolved' ? 'Đã giải quyết' : 'Từ chối'}</span><h3>{item.kind} · {item.reporterName} ({item.reporterRole})</h3><p>{item.description}</p>{item.submissionId && <p>Mã bài: {item.submissionId}</p>}<small>Gửi lúc: {new Date(item.createdAt).toLocaleString('vi-VN')}</small>{item.resolution && <p><b>Phản hồi:</b> {item.resolution}</p>}{['open', 'in_review'].includes(item.status) && <><Field label="Ghi chú xử lý (ít nhất 20 ký tự)"><textarea maxLength={3000} value={resolution} onChange={e => setResolution(e.target.value)} /></Field><div className="rw-actions"><button className="rw-secondary" disabled={busy || resolution.trim().length < 20} onClick={() => mutate(`/admin/complaints/${item.id}`, { status: 'in_review', resolution }, 'PATCH')}>Nhận xử lý</button><button className="rw-primary" disabled={busy || resolution.trim().length < 20} onClick={() => mutate(`/admin/complaints/${item.id}`, { status: 'resolved', resolution }, 'PATCH')}>Đóng với kết quả</button><button disabled={busy || resolution.trim().length < 20} onClick={() => mutate(`/admin/complaints/${item.id}`, { status: 'rejected', resolution }, 'PATCH')}>Từ chối có lý do</button></div></>}</article>;
}
function TicketHistory({ items }) {
  return <div className="rw-list">{items.map(item => <article className="rw-panel" key={item.id}><span className={`rw-badge rw-status-${item.status}`}>{item.status === 'open' ? 'Mới' : item.status === 'in_review' ? 'Đang xử lý' : item.status === 'resolved' ? 'Đã giải quyết' : 'Từ chối'}</span><h3>{item.kind === 'payout' ? 'Vấn đề thu nhập' : item.kind === 'review' ? 'Khiếu nại review' : 'Yêu cầu hỗ trợ'}</h3><p>{item.description}</p><small>{item.createdAt ? new Date(item.createdAt).toLocaleString('vi-VN') : ''}</small>{item.resolution && <p><b>Phản hồi admin:</b> {item.resolution}</p>}</article>)}</div>;
}
function Payment({ order: o, busy, mutate }) {
  const [reference, setReference] = useState(''), [verified, setVerified] = useState(false);
  return <article className="rw-panel rw-admin-item"><h3>{o.studentName || o.name || o.userId || o.orderId}</h3><p>{o.planLabel || o.planName || o.planId} · {money(o.price ?? o.amount)} · {o.status}</p>{o.status === 'completed' && <p>Hạn gói: {o.expiresAt ? new Date(o.expiresAt).toLocaleDateString('vi-VN') : 'Chưa có dữ liệu hết hạn'}</p>}<p>Mã đơn: {o.orderId} · Mã/nội dung chuyển khoản: {o.transactionCode || 'Chưa có'}</p>{!['completed', 'cancelled'].includes(o.status) && <><Field label="Mã giao dịch đối soát hoặc lý do hủy (ít nhất 5 ký tự)"><input maxLength={160} value={reference} onChange={e => setReference(e.target.value)} /></Field><label className="rw-check"><input type="checkbox" checked={verified} onChange={e => setVerified(e.target.checked)} />Tôi đã kiểm tra tiền thực nhận và thông tin người thanh toán.</label><div className="rw-actions"><button className="rw-primary" disabled={busy || !verified || reference.trim().length < 5} onClick={() => mutate(`/admin/orders/${o.orderId}`, { status: 'completed', reference }, 'PATCH')}>Xác nhận đã nhận tiền</button><button className="rw-secondary" disabled={busy || reference.trim().length < 5} onClick={() => mutate(`/admin/orders/${o.orderId}`, { status: 'cancelled', reference }, 'PATCH')}>Hủy đơn</button></div></>}</article>;
}
function RewardList({ submissions, catalog, admin, busy, mutate }) {
  const entries = submissions.filter(s => s.reward && Number(s.reward.base) > 0);
  return entries.length ? <div className="rw-list">{entries.map(s => <Reward key={idOf(s)} submission={s} title={catalog.find(c => c.id === s.challengeId)?.title} admin={admin} busy={busy} mutate={mutate} />)}</div> : <Empty>Chưa có phí review được ghi nhận.</Empty>;
}
function Reward({ submission: s, title, admin, busy, mutate }) {
  const [reference, setReference] = useState(''), [verified, setVerified] = useState(false);
  const eligibleAt = Date.parse(s.reviewedAt) + 7 * 86400000;
  const payoutEligible = !!s.rating || (Number.isFinite(eligibleAt) && Date.now() >= eligibleAt);
  return <article className="rw-panel"><h3>{title || s.challengeId}</h3><p>{s.review?.mentorName || s.mentorName || s.mentorId} · Cơ bản {money(s.reward.base)} + thưởng {money(s.reward.bonus)}</p><span className="rw-badge">{s.reward.paid ? 'Đã chi trả' : 'Chờ chi trả'}</span>{s.reward.paymentRef && <p>Mã chi trả: {s.reward.paymentRef}</p>}{admin && !s.reward.paid && payoutEligible && <><Field label="Mã giao dịch chi trả thực tế"><input maxLength={160} value={reference} onChange={e => setReference(e.target.value)} /></Field><label className="rw-check"><input type="checkbox" checked={verified} onChange={e => setVerified(e.target.checked)} />Đã chuyển khoản và đối soát với mentor.</label><button className="rw-primary" disabled={busy || !payoutEligible || !verified || reference.trim().length < 5} onClick={() => mutate(`/admin/payouts/${idOf(s)}`, { reference })}>Ghi nhận đã chi trả bài này</button></>}{admin && !s.reward.paid && !payoutEligible && <p className="rw-alert">Chưa đủ điều kiện chi trả. Chờ sinh viên đánh giá hoặc đến {Number.isFinite(eligibleAt) ? new Date(eligibleAt).toLocaleString('vi-VN') : 'khi có ngày hoàn thành hợp lệ'}. Chưa chuyển tiền cho khoản này.</p>}</article>;
}
